### ISSUE TITLE
Адаптация к преобразователю порта RS-232 в Ethernet

### ISSUE THREAD

**Issue by minzak** [akalagov/Aswega#1]
Реально ли адаптировать не к локальному порту, а к TCP релею ?
Есть один из распространенных девайсов - USR-DR301, преобразователь порта RS-232 в Ethernet.
Чтобы на базе него сделать удаленный съем информации.

Полезные линки:
https://www.pusr.com/products/din-rail-rs232-to-ethernet-converters-usr-dr301.html
https://usr24.ru/catalog/ethernet_preobrazovateli_v_rs232_rs485/usr_dr301/
https://usr24.ru/services/primery-primeneniya/podklyuchenie-kkt-atol-25f-k-ethernet/
https://usr24.ru/services/primery-primeneniya/dispetcherizatsiya-elektroschetchika-merkuriy-po-ethernet/
https://usr24.ru/services/primery-primeneniya/primer-podklyucheniya-teplovychislitelya-vkt-7/

Спасибо.

**Comment by akalagov** [comment]
А эти скрипты и работали не через физический порт, а через виртуальный COM-порт на компьютере, а к счетчику, соответственно, был подключен преобразователь Ethernet<->RS-232 (в моем случае одна из моделей с Tibbo Serial Server). Предполагаю, что для указанного Вами устройства тоже есть драйвер виртуального порта...
Сейчас в планах реализация функционала работы с прибором через устройство на базе ESP32 с ESPHome для считывания текущих данных в Home Assistant с возможностью удаленного считывания статистических данных с помощью программ типа AswegaM 2.0
